/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-tertiary": "#2a3044",
        "surface-container-highest": "#2f3445",
        "tertiary": "#d2d7f2",
        "surface-dim": "#0e1322",
        "secondary-container": "#3f2bb8",
        "surface-bright": "#343949",
        "outline": "#84948f",
        "primary-container": "#00d4b8",
        "surface-container": "#1a1f2f",
        "on-secondary-fixed-variant": "#3f2bb8",
        "on-primary-fixed-variant": "#005045",
        "on-background": "#dee1f7",
        "secondary-fixed": "#e4dfff",
        "on-surface": "#dee1f7",
        "on-tertiary-container": "#454b61",
        "on-surface-variant": "#bacac5",
        "on-secondary-fixed": "#150066",
        "surface-container-low": "#161b2b",
        "on-error": "#690005",
        "primary-fixed-dim": "#26dec2",
        "on-tertiary-fixed": "#151b2e",
        "on-tertiary-fixed-variant": "#40465b",
        "on-secondary": "#2700a1",
        "inverse-on-surface": "#2b3040",
        "inverse-surface": "#dee1f7",
        "secondary": "#c6c0ff",
        "inverse-primary": "#006b5c",
        "on-primary-container": "#00564a",
        "surface-tint": "#26dec2",
        "surface-variant": "#2f3445",
        "error-container": "#93000a",
        "outline-variant": "#3b4a46",
        "tertiary-fixed-dim": "#c0c5df",
        "on-primary-fixed": "#00201b",
        "on-primary": "#00382f",
        "tertiary-fixed": "#dce1fc",
        "error": "#ffb4ab",
        "background": "#0e1322",
        "primary-fixed": "#55fbde",
        "surface-container-lowest": "#090e1c",
        "secondary-fixed-dim": "#c6c0ff",
        "surface-container-high": "#25293a",
        "primary": "#46f1d3",
        "surface": "#0e1322",
        "tertiary-container": "#b7bcd5",
        "on-secondary-container": "#b3acff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "base": "8px",
      },
      fontFamily: {
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "metric-display": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "metric-display": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "code-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      gridTemplateColumns: {
        13: "40px repeat(12, 1fr)",
      },
    },
  },
  plugins: [],
};
